name: Feature Request
description: 建议一个新功能
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 描述你希望添加的功能
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 使用场景
      description: 为什么需要这个功能？你的使用场景是什么？
